# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "radiant-polls-extension"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chase James", "David Cato", "Andrew vonderLuft"]
  s.date = "2013-02-27"
  s.description = "Enables polls on pages. Uses cookies instead of sessions"
  s.email = "avonderluft@avlux.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "CHANGELOG",
    "HELP.textile",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/polls_controller.rb",
    "app/controllers/poll_response_controller.rb",
    "app/models/option.rb",
    "app/models/poll.rb",
    "app/views/admin/polls/_form.html.haml",
    "app/views/admin/polls/_option.html.haml",
    "app/views/admin/polls/edit.html.haml",
    "app/views/admin/polls/index.html.haml",
    "app/views/admin/polls/new.html.haml",
    "app/views/admin/polls/remove.html.haml",
    "config/locales/en.yml",
    "config/locales/en_available_tags.yml",
    "config/routes.rb",
    "db/migrate/001_create_polls.rb",
    "db/migrate/002_create_options.rb",
    "db/migrate/003_add_start_date_to_polls.rb",
    "lib/poll_process.rb",
    "lib/poll_tags.rb",
    "lib/tasks/polls_extension_tasks.rake",
    "polls_extension.rb",
    "public/images/admin/new-poll.png",
    "public/images/admin/poll.png",
    "public/images/admin/recycle.png",
    "public/images/admin/reset.png",
    "public/javascripts/admin/date_selector.js",
    "public/javascripts/admin/polls.js",
    "public/javascripts/poll_check.js",
    "public/stylesheets/admin/polls.css",
    "public/stylesheets/polls.css",
    "spec/controllers/admin/polls_controller_spec.rb",
    "spec/controllers/poll_response_controller_spec.rb",
    "spec/integration/page_caching_spec.rb",
    "spec/lib/poll_tags_spec.rb",
    "spec/models/poll_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/avonderluft/radiant-polls-extension"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Polls Extension for Radiant CMS"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 1.1.3"])
      s.add_runtime_dependency(%q<radiant-cache_by_page-extension>, [">= 1.0.2"])
    else
      s.add_dependency(%q<radiant>, [">= 1.1.3"])
      s.add_dependency(%q<radiant-cache_by_page-extension>, [">= 1.0.2"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 1.1.3"])
    s.add_dependency(%q<radiant-cache_by_page-extension>, [">= 1.0.2"])
  end
end

